### ISSUE TITLE
Continuous delivery

### ISSUE THREAD

**Issue by wrongware** [wrongware/projektak#20]
I need resolve CD process from Travis to demo https://projektak.wrongtest.cz/

**Comment by patriksima** [comment]
Is that possible to move CI files to own folder? What do you think?

**Comment by patriksima** [comment]
Please try Travis + Github Releases

**Comment by patriksima** [comment]
Hi, according to your last message you have to add to deployment process a few commands to trigger composer, npm updates.. It's not possible to do it manually.

**Comment by patriksima** [comment]
I really need to resolve this issue because I want to show the demo.

**Comment by patriksima** [comment]
Hi, I am not sure how to test it. But I believe that it's working. We need update dev help for social login setup.
