### ISSUE TITLE
Time Requests

### ISSUE THREAD

**Issue by patriksima** [wrongware/projektak#52]
Hi,

As Project Manager needs to show time requests from my team in section called Time Requests.

I need:
1. to approve these - a worker see a task
2. to deny these - a worker doesn't see a task and he should be notified about this somehow
3. to hide these from section Tasks

**Comment by patriksima** [comment]
I've checked this and I am not sure it's correct. There are some tasks with Time Request status in Tasks section (3). And if I've denied any time request, user haven't noticed about this (2).
It would be awesome to connect default user no. 1 with default worker. Because I can't test task assignment and other functionalities.

**Comment by kouks** [comment]
You are being noticed via email. Email driver is however set to `log` on stage.
